/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/cook/dishes`; params?: Router.UnknownInputParams; } | { pathname: `/cook`; params?: Router.UnknownInputParams; } | { pathname: `/cook/orders`; params?: Router.UnknownInputParams; } | { pathname: `/eat/cart`; params?: Router.UnknownInputParams; } | { pathname: `/eat/checkout`; params?: Router.UnknownInputParams; } | { pathname: `/eat`; params?: Router.UnknownInputParams; } | { pathname: `/eat/menu`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/cook/dishes`; params?: Router.UnknownOutputParams; } | { pathname: `/cook`; params?: Router.UnknownOutputParams; } | { pathname: `/cook/orders`; params?: Router.UnknownOutputParams; } | { pathname: `/eat/cart`; params?: Router.UnknownOutputParams; } | { pathname: `/eat/checkout`; params?: Router.UnknownOutputParams; } | { pathname: `/eat`; params?: Router.UnknownOutputParams; } | { pathname: `/eat/menu`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/cook/dishes${`?${string}` | `#${string}` | ''}` | `/cook${`?${string}` | `#${string}` | ''}` | `/cook/orders${`?${string}` | `#${string}` | ''}` | `/eat/cart${`?${string}` | `#${string}` | ''}` | `/eat/checkout${`?${string}` | `#${string}` | ''}` | `/eat${`?${string}` | `#${string}` | ''}` | `/eat/menu${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/cook/dishes`; params?: Router.UnknownInputParams; } | { pathname: `/cook`; params?: Router.UnknownInputParams; } | { pathname: `/cook/orders`; params?: Router.UnknownInputParams; } | { pathname: `/eat/cart`; params?: Router.UnknownInputParams; } | { pathname: `/eat/checkout`; params?: Router.UnknownInputParams; } | { pathname: `/eat`; params?: Router.UnknownInputParams; } | { pathname: `/eat/menu`; params?: Router.UnknownInputParams; };
    }
  }
}
